language: ruby
os: linux
dist: focal

addons:
  chrome: stable
  postgresql: 13

env:
  global:
    - BUNDLE_DEPLOYMENT=true
    - BUNDLE_JOBS=4
    - BUNDLE_RETRY=3
    - BUNDLE_WITHOUT=development:production
    - RAILS_ENV=test

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - vendor/bundle

before_install:
  - nvm install --lts
  - node --version

install:
  - bundle install
  - yarn install --frozen-lockfile

before_script:
  - bin/rails db:create
  - bin/rails webpacker:compile

script:
  - bundle exec rubocop --parallel
  - bin/rails zeitwerk:check
  - bin/rails test
  - bin/rails test:system

notifications:
  email: false
