language: ruby
os: linux
dist: focal

addons:
  chrome: stable
  postgresql: 13

env:
  global:
    - BUNDLE_DEPLOYMENT=true
    - BUNDLE_JOBS=4
    - BUNDLE_RETRY=3
    - BUNDLE_WITHOUT=development:production
    - RAILS_ENV=test

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - vendor/bundle

before_install:
  - nvm install 12.18
  - node --version

install:
  - bundle install
  - yarn install --frozen-lockfile

before_script:
  - bundle exec rails db:create
  - bundle exec rails webpacker:compile

script:
  - bundle exec rails zeitwerk:check
  - bundle exec rubocop --parallel
  - bundle exec rails test
  - bundle exec rails test:system

notifications:
  email: false
