dist: bionic
language: ruby

addons:
  chrome: stable
  postgresql: 10

cache:
  bundler: true
  yarn: true

  directories:
    - node_modules
    - vendor/bundle

before_install:
  - bundle config set deployment 'true'
  - bundle config set without 'development:production'

install:
  - bundle install --jobs=3 --retry=3
  - yarn install --frozen-lockfile

before_script:
  - RAILS_ENV=test bundle exec rails db:create

script:
  - bundle exec rails test
  - bundle exec rails test:system
  - bundle exec rails zeitwerk:check
  - bundle exec rubocop --parallel

notifications:
  email: false
