dist: bionic
language: ruby

addons:
  chrome: stable
  postgresql: 10

cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle
  yarn: true

before_install:
  - gem update --system --no-document
  - gem --version
  - gem install bundler --no-document
  - bundler --version

install:
  - bundle install --jobs=3 --retry=3 --without=development:production
  - yarn install

before_script:
  - RAILS_ENV=test bundle exec rails db:create

script:
  - bundle exec rails test:system test
  - bundle exec rubocop --parallel

notifications:
  email: false
