version: '3'

services:
  web:
    build: .
    command: /bin/bash -c "bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db

  db:
    image: postgres:10-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  gem_cache:
  node_modules:
  pgdata:
