default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: upupa_development

test:
  <<: *default
  database: upupa_test

production:
  <<: *default
  database: upupa_production
