name: CI

on:
  push:
    branches: [main]
    paths-ignore: [README.md]
  pull_request:
    branches: [main]
    paths-ignore: [README.md]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: upupa_test
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: development:production
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: bundle exec brakeman --run-all-checks
      - run: bundle exec standardrb
      - run: yarn run standard
      - run: bin/rails test:all
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/upupa_test
          RAILS_ENV: test
